services:
  prodqserv:
    image: sokol111/${PROJECT_NAME}:latest
    container_name: prodqserv
    labels:
      - "traefik.http.routers.prodqserv.rule=Host(`${PROJECT_NAME}.test`)"
      - "traefik.http.services.prodqserv.loadbalancer.server.port=8080"
    networks:
      - shared-network
    environment:
      - APP_ENV=development
      - MONGO_HOST=mongo
      - KAFKA_BROKERS=kafka:29092

networks:
  shared-network:
    external: true
