logger:
  level: "debug"
  development: true

server:
  port: 8080

mongo:
  host: "localhost"
  port: 27017
  database: "product-query"
  direct-connection: true

kafka:
  brokers: "localhost:9092"
  schema-registry:
    url: "http://localhost:8084"
    auto-register-schemas: true
  consumers-config:
    default-group-id: "ecommerce-product-query-service"
    default-auto-offset-reset: "earliest"
    consumers:
      - name: "catalog-events"
        topic: "catalog.product.events"
      - name: "catalog-attribute-events"
        topic: "catalog.attribute.events"

security:
  token:
    jwks-url: "http://localhost:8080/oauth/v2/keys"

observability:
  otel-collector-endpoint: ""
  tracing:
    enabled: true
  metrics:
    enabled: false