logger:
  level: "debug"
  development: true

server:
  port: 8080

mongo:
  host: "mongo"
  port: 27017
  database: "product-query"
  replica-set: rs0
  migrations:
    enabled: true
    auto-migrate: true

kafka:
  brokers: "kafka:29092"
  schema-registry:
    url: "http://schema-registry:8081"
    auto-register-schemas: true
  consumers-config:
    default-group-id: "ecommerce-product-query-service"
    default-auto-offset-reset: "earliest"
    consumers:
      - name: "product-events"
        topic: "catalog.product.events"

observability:
  otel-collector-endpoint: "otel-collector-opentelemetry-collector.observability.svc:4317"
  tracing:
    enabled: true
  metrics:
    enabled: false
