logger:
  level: "debug"

server:
  port: 8080

mongo:
  host: "localhost"
  port: 27017
  replica-set: rs0
  #  username: "root"
  #  password: "password"
  database: "product-query"

kafka:
  brokers: "localhost:9092"
  consumers-config:
    group-id: "ecommerce-product-query-service"
    auto-offset-reset: "earliest"
    consumers:
      - handler: "productCreatedHandler"
        topic: "catalog.product.created.v1"
      - handler: "productUpdatedHandler"
        topic: "catalog.product.updated.v1"
