logger:
  level: "debug"
  development: true

server:
  port: 8080

mongo:
  host: "mongo"
  port: 27017
  database: "product-query"
  replica-set: rs0

kafka:
  brokers: "redpanda:29092"
  schema-registry:
    url: "http://redpanda:8081"
    auto-register-schemas: true
  consumers-config:
    default-group-id: "ecommerce-product-query-service"
    default-auto-offset-reset: "earliest"
    consumers:
      - name: "catalog-events"
        topic: "catalog.product.events"
        max-retries: 5
        initial-backoff: 2s
        max-backoff: 30s
        enable-dlq: true
      - name: "catalog-attribute-events"
        topic: "catalog.attribute.events"
        max-retries: 5
        initial-backoff: 2s
        max-backoff: 30s
        enable-dlq: true
      - name: "tenant-events"
        topic: "tenant.tenant.events"
        max-retries: 5
        initial-backoff: 2s
        max-backoff: 30s
        enable-dlq: true

security:
  token:
    jwks-url: "http://zitadel-api:8080/oauth/v2/keys"
  s2s:
    client-id: "311056156296133365"
    private-key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC7UpIfGcIUd6Qr
      WS7QjyyPks6YyhgGfYXBngS2V6RITOkmaFQsuQVzxquMmBp3W7Gw2dbhVyVnZTqY
      qMFYFwk+N/0AEMId9+X3H54lobSayfd07OwvW1dMGQR7KUI8t/MXqR+JTtiRCTRs
      RzVVkxajozuqAT84eI23kHgP8Eh1g+2ejzzxE/QA20IiIBTUH8CrgvjCn5JUUz/b
      PIQGFqAb4QlzdPVzTkvTRrdm7dmfu2cjM0axmfExRZ99J5MTIL0mp5gxN4gYXSu6
      5wjCwOgkiwkokdYeQUjT2wAPQOe+XmS91WIgLUNcSKwbDEdiGPV7uorY88w987G2
      ccAFE/h9AgMBAAECggEAD6+XsW4DpmYcXU4Zavjj3apVjYE2ANK7BB5HPVbaci/d
      wcvjtiw28vdBP0OVyvmAYcaw3tH6ClrCM0b4v13ydeWg7hDF+7xAYz2GpzBCz0fR
      TNbxsi3lm5qbf8Ee0FA3bxUU7hEOdoEWuDVASvtHRPDZNEbop3U4D/wgUA/Dz/Ju
      6qsUMI3EP0A6scjPL2NXSMdIQ4ijewgZE1zY/2c4ATCGbU0+pxkLsj25L48E63Wt
      MZqq+LUHcpAxMLhBuJ33w86yeFJWudpvp7xnKmUFWCwBCRTH/X0e6mAqa8z1/b9K
      UGhxy9C2ZxD/dhEpVB5uFu2jPyCUtzNNJM5E2KkJWwKBgQDteHNvHSM/vjEzYvbh
      z/zXSl1Tx5sUqT5mmWJjADBaAdblViLxtQYxhngQdZWu/5D8yniFBGA8Ou4NpOki
      mRnJ7fNcOv9nDzBMrXVZaMY2UhXVQmwfiplMis8NWgykvRpO48cOvzprfvDGEGQH
      LngbSZkWGfiaHkMuYq/D73t9gwKBgQDJ8GXxmv6Lah7OaelQ77U9FquXqpsAEKdq
      paslmy6SxalC9i8XYVEXk4612P+f8lFa0E3ot7UL6PT2ZhRx4cqptvCvwDNLSQ6S
      rnwKb8dPV/sknPXahUFjM1QE/tWVzg56rB+fY5MRt/NCPRBoJbhE7ujXJtsb94GM
      4WBF8N7R/wKBgHYEGIouFuiE4vrAwiUzMlrkUEFkv8Oi4KoorGa7H0x8AYp0JmWt
      K2jNhTnY1gzkYe/fx8mDhTgpqUkKnfpd0B00rm81utxDBiP1SI6orWktnkAgBJAg
      V1Nc4M2n5QSyHjL6rGC91JC7w3kLiEqxY2tcRkJfodcmFwkkbmmXyO11AoGAFT7c
      itnCtAo7KX5NFL3TdJThArjpS810v6ykX/V+peRz1V6vP6d2b6OPnSQyaLKGyqYl
      vDkvrAwbUZ0Vw5F8z/Q2SFdRTjdmeBoxZKuz7W4VNxnoZ9AjO/uXeFsTP4qJTXC0
      dwFz5KZUyoBALKTjSSVVi+VDoiKdF6RSi6k22CMCgYAVcFDFwv7WoTVTAIzhq+Q+
      GAxoHxIp5r8He24fbXxGYYq5P+IRR6H6rCm8MFyM/FdblqPreq+PG2UX5aJVOCQB
      XrL2W8DIYSrQE14JRJMeC//M181UTZf8u0OZe3l2W9oGU/UTzd11rq4A6qmnrg/9
      8zdoZABIhwT1qRlmmUNxZA==
      -----END PRIVATE KEY-----
    token-url: "http://zitadel-api:8080/oauth/v2/token"

observability:
  otel-collector-endpoint: "otel-collector-opentelemetry-collector.observability.svc:4317"
  tracing:
    enabled: true
  metrics:
    enabled: false

pprof:
  enabled: true
  port: 6060

clients:
  tenant-service:
    base-url: "http://ecommerce-tenant-service:8080"
