logger:
  level: "debug"

server:
  port: 8080

mongo:
  host: "localhost"
  port: 27017
  database: "product-query"
  direct-connection: true
  migrations:
    enabled: true
    auto-migrate: true

kafka:
  brokers: "localhost:9092"
  schema-registry:
    url: "http://localhost:8084"
    cache-capacity: 1000
  consumers-config:
    group-id: "ecommerce-product-query-service"
    auto-offset-reset: "earliest"
    consumers:
      - name: "product-events"
        topic: "catalog.product.events"

observability:
  tracing-enabled: true
  otel-collector-endpoint: ""
